global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blockhouse_streaming_api'
    static_configs:
      - targets: ['api:8088']
    metrics_path: /metrics

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda-0:9644']
    metrics_path: /public_metrics